hypertrons/hypertrons-crx

.github/hypertrons.json

Signed-off-by: Frankzhaopku <syzhao1988@126.com>
Add Hypertrons menbotics config file

feat: add hypertrons config file

---

.github/hypertrons.json
package-lock.json

- Update weekly report on every Wednesday.
- Add @LiuChangFreeman to commiter and approver.
- Add package-lock.json

feat: update hypertrons config file

---

CONTRIBUTING.md

Signed-off-by: 梅佳奕 <10165300206@stu.ecnu.edu.cn>

fix: update contributing guide

---

src/pages/Content/components/DeveloperCollabrationNetwork/index.tsx
src/pages/Content/components/DeveloperCollabrationNetwork/sample.data.ts

feat: add developer collabration network component

---

.github/pull_request_template.md
CONTRIBUTING.md

fix: add a Pull-Request template

Pr template

---

.github/workflows/build.yml

We need only create pre-releases on push events.
_Describe the problem or feature in addition to a link to the issues._
_If this is a relatively large or complex change, kick off the discussion …

fix: disable auto-build on pull-requests

---

src/components/OptionsPage/index.tsx
src/components/PopupPage/index.tsx
src/utils/settings.ts
src/utils/utils.ts

In this commit, developers can use the `Settings` to load/store configuration everywhere. 
_See https://github.com/hypertrons/hypertrons-crx/issues/74_
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc..._
_Links to blog posts, patterns, libraries or addons used to solve this …

feat: introduce global settings api

---

.github/workflows/pull_request_test_build.yml

This will introduce another `ci` called `test-build` which will work when a pull request is open to check whether it can build the `.crx` successfully. Also the `pre-release` will make this check before making a new pre-release.   
_See https://github.com/hypertrons/hypertrons-crx/issues/65._
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose …

feat: improve the ci&cd workflows

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/OptionsPage/index.tsx
src/mock/background.data.ts
src/pages/Background/index.ts
src/services/background.ts
src/services/common.ts
src/utils/metadata.ts
src/utils/settings.ts
src/utils/utils.ts

This pr implements the UI of update feature. 
When an update is available, the notification will occur every 24 hours unless the user disable it in options page.
Users can also check for update manually in options page.
If an update is available, an hyperlink will be shown to guide user to the install page which can be different for different installation type.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, …

feat: notification & button for updates

---

.github/workflows/build.yml

This pr changes the `ci` pre-release to enable sync the folder `src/mock` to our oss bucket using this action: https://github.com/marketplace/actions/upload-to-oss  
We can server the update information by requesting an json file in oss and publish the latest information by pr. 
The manager need to fill the secrets needed by the oss action.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure …

feat: publish asserts to oss

---

.github/workflows/build.yml
publish/update_information.json

Add a new folder `publish` to store information and upload that to oss by `ci`.
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …

refactor: upload publish information to oss

---

INSTALLATION.md
README.md

add an installation guide (with common browsers: Edge, Chrome, 360 Apeed & 360 Safety)
INSTALLTION.md is added to the root directory.

doc: add installation guide #85

---

src/pages/Content/features/developer-network.tsx
src/pages/Content/features/index.tsx
src/pages/Content/features/project-network.tsx

- get the correct URL for `projectNetwork` graph.
- fix the wrong reference of `.css`.
- add `log` to `feature` object.

fix: update project network

---

src/components/OptionsPage/index.tsx
src/pages/Background/index.ts
src/services/background.ts

This pr change the update url to this:  
https://hypertrons.oss-cn-shanghai.aliyuncs.com/crx-release/update_information.json  
It will be used for publish update information from now on.  
_If …

fix: change update url

---

README.md
src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/Perceptor.tsx
src/pages/Content/PerceptorBase.tsx
src/pages/Content/PerceptorLayout.tsx
src/pages/Content/PerceptorTab.tsx
src/pages/Content/ProjectNetwork.tsx
src/pages/Content/index.ts
src/utils/utils.ts

In #93 , we introduced the IOC mechanism to our project. However, when we want to add a new feature, we still need to modify `Perceptor` class. In this PR, we will try to implement IOC mechanism in another way.
- add `inject2Perceptor` function to inject the `feature` class to `Perceptor`:
```ts
export const inject2Perceptor = (constructor: Function): void => {
Perceptor.Features.set(constructor.name, constructor)
}
```
- Instantiate and run feature after checking `settings` and `include` 
```ts
// run every features
Perceptor.Features.forEach(async (Feature, name) => {
const featureId = name.replace(name[0],name[0].toLowerCase());
this.logger.info('trying to load ', featureId)
if (this.settings.toJson()[featureId] === false) {
this.logger.info(featureId, 'is disabled');
return;
}
if …
```

refactor: refactor IOC mechanism

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/OptionsPage/index.tsx
src/services/common.ts
src/utils/metadata.ts

This pr allows user to store `github token` in `MetaData` generated by this page:  
https://github.com/settings/tokens 
_If this is a relatively large or complex change, kick off the discussion …

feat: support for github token

---

src/api/index.ts
src/services/background.ts

Signed-off-by: frank-zsy <syzhao1988@126.com>
Change OSS file base URL into `http://hypertrons-oss.x-lab.info`.
More friendly URL under x-lab.info rather than aliyun.com
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc..._
_Links to blog posts, patterns, libraries or addons used to solve this problem_

[Refactor] Change OSS base URL into x-lab.info

---

src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/PerceptorTab.tsx
src/pages/Content/ProjectBase.tsx
src/pages/Content/TeachingBubbleWrapper.tsx

Now teaching bubble is ready in  `perceptor tab`:  
Also the position is changed in project view:  
_If this is a relatively large or complex change, kick off the discussion by explaining why you …

feat:add teaching bubble for perceptor tab

---

publish/notification.json
src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/OptionsPage/index.tsx
src/mock/background.data.ts
src/pages/Background/index.ts
src/pages/Content/TeachingBubbleWrapper.tsx
src/services/background.ts
src/utils/metadata.ts

Now we can publish notification to users when they open the `options page` by modifying the `publish/notification.json`  
This can be used for urgent messages and here is an example:  
```
{
"id": 2021052301,
"content": {
"zh": "欢迎使用Hypertrons!",
"en": "Welcome to Hypertrons!"
},
"is_published": true
}
```
Each time we can change the field `id` and `is_published`. If user chooses `Don't show this again`, the `id` will be cached in local storage. Next notification will appear only when the remote `id` is bigger than local.  …

feat: add notification for options page

---

src/manifest.json
src/pages/Background/index.ts

Now we don't need the `tabs` privilege
- [x I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)
_If this is a relatively large or complex change, kick off the discussion …

fix: remove tabs

---

src/components/OptionsPage/index.tsx

fix bug causing cpu high load in `options page` 
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …

fix: cpu high load bug

---

package.json
publish/update_information.json
src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/OptionsPage/index.tsx
src/mock/background.data.ts

We can tell users how these settings will work using tooltip in `options page`. 
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …

feat: add tooltip to options page

---

publish/update_information.json

After publishing a formal release to Chrome or Microsoft store, we should update this file to the latest. 
_If this is a relatively large or complex change, kick off the discussion by explaining …

refactor: update update_information.json

---

src/pages/Content/PerceptorTab.tsx

refer to: https://github.com/hypertrons/hypertrons-crx/issues/145
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …

fix: redundant clone bug

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/ExceptionPage/ErrorMessageBar.tsx
src/components/ExceptionPage/ErrorPage.tsx
src/components/Graph/Graph.tsx
src/components/Graph/Graphin/index.tsx
src/components/OptionsPage/index.tsx
src/components/PopupPage/index.tsx
src/pages/Background/index.ts
src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/ProjectNetwork.tsx
src/pages/Content/TeachingBubbleWrapper.tsx
src/utils/settings.ts
src/utils/utils.ts

This pr introduces the `getMessageByLocale` api to help implement the feature `choose language manually`.  https://github.com/hypertrons/hypertrons-crx/issues/143  
~~This pr doesn't fully support the feature but the UI is complete.~~  
```
export function getMessageByLocale(key: string,locale:string) {
// @ts-ignore
return messages_locale[locale][key]["message"];
}
```
- [] Bugfix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing …

feat: choose language manually

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/Graph/Graph.tsx
src/constant.ts
src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/ProjectNetwork.tsx

refactor: remove dark mode

---

src/pages/Content/PerceptorLayout.tsx
src/pages/Content/ProjectNetwork.tsx

The previous pr will cause a bug: the spinner doesn't disappear.  https://github.com/hypertrons/hypertrons-crx/pull/152  
This pr fixs it.  
_If this is a relatively large or complex change, kick …

fix: bug caused by pr 152

---

src/components/OptionsPage/index.tsx

fix locale bug in notification
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

fix: locale bug in options page

---

README.md

These minor changes help the newcomers to clone the repo without having the issue instead of configuring ssh one.

feat: update the cloning process

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/ExceptionPage/ErrorMessageBar.tsx
src/components/ExceptionPage/ErrorPage.tsx
src/components/Graph/Graph.tsx
src/constant.ts
src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/ProjectNetwork.tsx
src/utils/request.ts

refactor: add friendly notification if data not found

---

.github/issue_template.md

Simple Typo fix in the Issue_template
The issue template had a typo in line 21. This PR simply fixes it 

Typo fix in Issue_template

---

publish/update_information.json

update v1.0.1 in update_information.json

release v1.0.1

---

src/pages/Content/PerceptorTab.tsx

Fix issue https://github.com/hypertrons/hypertrons-crx/issues/165  
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …

fix: perceptor menu item bug

---

package.json
src/components/OptionsPage/index.css
src/pages/Options/index.css

Theme of `options page` now is the same as github.
- [] Bugfix (non-breaking change which fixes an issue)
_If this is a relatively large or complex change, kick off the discussion by explaining …

feat: change theme of options page

---

README.md
src/pages/Content/PerceptorTab.tsx

Signed-off-by: Ayush PS <ayushpratap16@gmail.com>
Fixes typos in the `README` and the Perceptor tab in  three-dot menu

Some typos fixed in docs and Data Item Link

---

package.json
publish/update_information.json
src/components/OptionsPage/index.tsx
src/components/PopupPage/index.tsx
src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/manifest.json
src/pages/Content/DeveloperNetwork.tsx
webpack.config.js

Chang name to `Hypercrx` and update version to v1.0.2 
This pr removes remove unnecessary unsafe-eval in `manifest.json` 
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc..._
_Links to blog posts, patterns, libraries or addons used to solve this problem_

release v1.0.2

---

src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/ProjectNetwork.tsx

add @ts-ignore in some codes
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …

fix: bug blocking build

---

package.json
src/components/DynamicBar/DynamicBar.tsx
src/components/DynamicBar/PlayButton/PlayButton.tsx

This PR implements the "DynamicBar" feature requested by #216.
The `DynamicBar` component is derived from [anichart.js](https://github.com/Jannchie/anichart.js) which is a really cool tool for visualizing time-based data.
`DynamicRadar` is really easy to use and provides features like:
- `light` & `dark` themes
- customizable sizes
- dynamic & intuitive
```typescript
import DynamicBar from '../../components/DynamicBar/DynamicBar';
const Demo = () => {
return (
<DynamicBar theme="light" width={800} height={600} barNumber={18} digitNumber={2} duration={10} dateLabelSize={60} dataUrl="http://127.0.0.1:9888/data.csv"/>
)
}
```
`DynamicBar` receives a dataUrl and then requests for the data by itself. The `.csv` data looks like this:
```
id,date,value
LiuChangFreeman,2020-11-05,1.44 …
```

feat: Add DynamicBar component.

---

.github/hypertrons.json

community: add @tyn1998 and @zhuxiangning to be the committer and approver

---

src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/content.styles.css

fix: update style of dialog for DeveloperNetwork and ProjectNetwork

---

.github/workflows/build.yml
src/components/DynamicRadar/Radar/Radar.tsx

Now the extension can be built and uploaded normally. 
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …

fix: bug blocking build and release

---

src/pages/Content/ProjectNetwork.tsx

[UI] Change column width of perceptor boxes

---

src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/pages/Content/ContributorsActivityEvolution.tsx
src/pages/Content/content.styles.css
src/pages/Content/index.ts

Inject "Contributor Activity Rolling Chart", which is based on [DynamicBar](https://github.com/hypertrons/hypertrons-crx/pull/207), into Perceptor Tab. #233 #234 
Each Contributor Activity Rolling Chart corresponds to a csv file which is generated by [X-lab](https://github.com/X-lab2017).
English:
中文:

[feature] Add Contributor Activity Rolling Chart Perceptor Tab.

---

src/pages/Content/ContributorsActivityEvolution.tsx
src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/ProjectNetwork.tsx

Some UI changes such as column width change and css margin modification.

[UI] Minor changes

---

.github/workflows/build.yml

Inconsistent names cause CI error, so solve these mistakes.

[workflow] change all "hypertrons-crx" to "hypercrx" in build.yml

---

src/components/Graph/Graph.tsx

[fix] made color of focused node in Graph red again

---

package.json

[prettier] stop prettify md files

---

src/pages/ContentScripts/PerceptorTab.tsx

[UI] fix wrongly selected tab

---

package.json
publish/update_information.json
src/manifest.json

[manifest] remove management permission from manifest.json

---

README.md
README.zh-CN.md

This PR is initiated by https://github.com/hypertrons/hypertrons-crx/issues/312.

[WIP] [Doc] Update links in README

---

package.json
publish/update_information.json
src/api/developer.ts
src/api/repo.ts
src/components/Bars/index.tsx
src/constant.ts
src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/mock/background.data.ts
src/pages/ContentScripts/DeveloperActiInflTrend.tsx
src/pages/ContentScripts/RepoActiInflTrend.tsx
src/pages/ContentScripts/index.ts
src/utils/request.ts

This PR is initiated by #297, and any updates will be put here.

new repo/developer activity & influence trend charts

---

.github/pull_request_template.md

- resolves #361 
I simplify the PR template as what you see in this PR description.
端午节快乐！

simplify pull_request_template.md

---

CONTRIBUTING.md
src/constant.ts

chore: update new issues url

---

src/pages/ContentScripts/Perceptor.tsx

- resolve #398
Just remove it from mainInject() and everything works fine.
N.A.

chore: remove an event listener that won't work

---

README.md
README.zh-CN.md

- resolve #411 
Recapture several screenshots and put them in README to replace the broken ones.
N.A.

docs: fix broken images in README

---

README.md
README.zh-CN.md

docs: removed link from opera icon in README

---

.github/hypertrons.json

- #420 
Grant @wxharry 3 roles of hypertrons. 🎉 
🎉

community: invite @wxharry to be one of the Hypercrx maintainers 🎉 

---

INSTALLATION.md
INSTALLATION.zh-CN.md
README.md
README.zh-CN.md

docs: fix broken image and change table style

---

package.json
yarn.lock

* #422 
Add package cross-env in `package.json`

fix: add package cross-env

---

README.md
README.zh-CN.md
package.json

docs: add node version requirement

---

src/anchors/PerceptorLayoutAnchor.tsx
src/anchors/PerceptorTabAnchor.tsx

- fix #439 
1. modify the way of finding insightTab
2. remove `data-selected-links` to improve performance

fix: failed to find insightsTab

---

utils/server.js

* #449 
update rules for `updatedJsModules` and `isContentScriptsUpdated`
Thanks @smitsekhadiaa for spotting this issue.
Thanks @tyn1998 for helping fix it.

bug: fix auto reload on locales

---

src/components/Bars/index.tsx
src/views/RepoActiInflTrendView/RepoActiInflTrendView.tsx

* #430 
I added functions on click event to accomplish what we want when clicking a bar.

feat: click activity bar to view all issues and PRs in that month

---

src/Perceptor.tsx

- fix https://github.com/hypertrons/hypertrons-crx/issues/463
modify the featureId

fix: perceptor components cannot be disabled

---

.github/workflows/issue-comment.yml
.github/workflows/issue-open.yml

ci: auto mark issue reply status

---

src/views/RepoDetailIssueView/IssueChart.tsx
src/views/RepoDetailPRView/MergedLinesChart.tsx
src/views/RepoDetailPRView/PRChart.tsx
src/views/RepoDetailPRView/RepoDetailPRView.tsx

- fix #473
adjust the width of tooltip

fix: the width of tooltip is too small

---

src/views/RepoDetailPRView/MergedLinesChart.tsx

fix: recenter the title of mergedline chart

---

src/anchors/DeveloperActInflTrendAnchor.tsx
src/anchors/DeveloperNetworkAnchor.tsx

- fix #479
Add if branches to avoid multiple renders.

fix: avoid redundant renders

---

README.zh-CN.md

docs: update Chinese README

---

README.md
README.zh-CN.md
src/anchors/RepoDetailForkAnchor.tsx
src/anchors/RepoDetailIssueAnchor.tsx
src/anchors/RepoDetailPRAnchor.tsx
src/anchors/RepoDetailStarAnchor.tsx
src/components/Bars/index.tsx
src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/pages/ContentScripts/index.scss
src/views/RepoDetailForkView/ForkChart.tsx
src/views/RepoDetailForkView/RepoDetailForkView.tsx
src/views/RepoDetailIssueView/IssueChart.tsx
src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
src/views/RepoDetailPRView/MergedLinesChart.tsx
src/views/RepoDetailPRView/PRChart.tsx
src/views/RepoDetailPRView/RepoDetailPRView.tsx
src/views/RepoDetailStarView/RepoDetailStarView.tsx
src/views/RepoDetailStarView/StarChart.tsx
src/views/RepoHeaderLabelsView/ActivityChart.tsx
src/views/RepoHeaderLabelsView/InfluenceChart.tsx
src/views/RepoHeaderLabelsView/ParticipantChart.tsx
src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx

- resolve #495
Try my best to work out what a designer suggests in [this](https://www.figma.com/file/lHPwpACIjHsGQp1sgW4flf/Work-with-Frank?node-id=471%3A0) Figma:

style: change popups style by a designer's guidance

---

src/anchors/RepoDetailForkAnchor.tsx
src/anchors/RepoDetailIssueAnchor.tsx
src/anchors/RepoDetailPRAnchor.tsx
src/anchors/RepoDetailStarAnchor.tsx
src/pages/ContentScripts/index.scss
src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx

- resolve #510 
make a slight change to the UI style according to the design, as shown in the screenshot below:

style: slight change of UI

---

src/api/developer.ts
src/api/repo.ts
src/components/Bars/index.tsx
src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/utils/data.ts
src/views/DeveloperActiInflTrendView/DeveloperActiInflTrendView.tsx
src/views/RepoActiInflTrendView/RepoActiInflTrendView.tsx
src/views/RepoDetailForkView/RepoDetailForkView.tsx
src/views/RepoDetailIssueView/IssueChart.tsx
src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
src/views/RepoDetailPRView/MergedLinesChart.tsx
src/views/RepoDetailPRView/PRChart.tsx
src/views/RepoDetailPRView/RepoDetailPRView.tsx
src/views/RepoDetailStarView/RepoDetailStarView.tsx
src/views/RepoHeaderLabelsView/ActivityChart.tsx
src/views/RepoHeaderLabelsView/InfluenceChart.tsx
src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx

refactor: use new API to refactor existing components

---

README.md
README.zh-CN.md

Signed-off-by: frank-zsy <syzhao1988@126.com>
Add OpenDigger project badge and link as OpenDigger suggest.

docs: Add OpenDigger badge.

---

src/utils/data.ts

I did something wrong in #542, which cannot properly handle the new date format. Horrible!
This PR should be merged ASAP! I have tested it with production data (both old and new).
old:
new:
😢

fix: fatal date parse error

---

NOTICE

- resolve #560
Add a NOTICE file.

docs: add a NOTICE file to apply the LICENSE to our work

---

.github/hypertrons.json

Update .github/hypertrons.json so @lhbvvvvv will have the the right to `/approve` PRs.

community: invite @lhbvvvvv to be one of the Hypercrx maintainers

---

src/views/DocsGPTChatWidget/index.tsx

- resolve #611
disable the unread badge:
https://user-images.githubusercontent.com/32434520/225508733-f1400824-8d90-410c-a14a-deed9da1ad82.mov
N.A.

style: disable chat widget badge (the red unread bubble)

---

src/locales/en/messages.json
src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
src/views/ProjectNetworkView/ProjectNetworkView.tsx

- keyword #618 
As mentioned in the related issue, the buttons of drop-down box in dark theme are ugly. Besides, I think that the drop-down box is not necessary because of  the single choice of the drop-down box. So I changed the drop-down box to text.

style: modify the drop-down box of network views

---

src/locales/en/messages.json

Reformat English messages

---

src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/views/DocsGPTChatWidget/index.tsx

- resolve #614
add i18n support for OSS-GPT chat widget.

feat: add i18n support for OSS-GPT chat widget

---

README.md
README.zh-CN.md

- #615
Added documentation for oss-gpt in Chinese and English README.
N.A.

docs: update Chinese and English README for OSS-GPT chat widget 

---

src/pages/ContentScripts/features/developer-networks/view.tsx
src/pages/ContentScripts/features/perceptor-tab/index.tsx
src/pages/ContentScripts/index.scss

-  #649 
- #647 
Merge the changes to the branch v1.9.0 made in the master branch in #650 and #648
N.A

fix: resolve alignment issues  (#649)

---

INSTALLATION.md
INSTALLATION.zh-CN.md
README.md
README.zh-CN.md
package.json
scripts/bump-version.cjs
src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/pages/ContentScripts/features/repo-activity-racing-bar/AvatarColorStore.ts
src/pages/ContentScripts/features/repo-activity-racing-bar/PlayerButton.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/RacingBar.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/SpeedController.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/data.ts
src/pages/ContentScripts/features/repo-activity-racing-bar/index.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/useLoadedAvatars.ts
src/pages/ContentScripts/features/repo-activity-racing-bar/view.tsx
src/pages/ContentScripts/index.scss
yarn.lock

- resolve #729
- resolve #234
In this PR I added media player controllers for the Racing Bar. I could say now the Racing Bar is the most complex feature in Hypercrx 😆 .
Video:
https://github.com/hypertrons/hypertrons-crx/assets/32434520/ec76ed01-11fc-4967-a124-5f2018328494
In `light` theme:
In `dark` theme:

feat: media player controllers for contributor activity racing bar

---

src/pages/ContentScripts/features/perceptor-layout/view.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/index.tsx
src/pages/ContentScripts/features/repo-networks/index.tsx

- Resolve #718 
1. Add `div` elements in the `perceptor-layout` 
2. Update where we add the graphs

fix: inconsistent graphs layout

---

src/components/Bars.tsx
src/pages/ContentScripts/features/repo-fork-tooltip/ForkChart.tsx
src/pages/ContentScripts/features/repo-header-labels/ActivityChart.tsx
src/pages/ContentScripts/features/repo-header-labels/OpenRankChart.tsx
src/pages/ContentScripts/features/repo-header-labels/ParticipantChart.tsx
src/pages/ContentScripts/features/repo-issue-tooltip/IssueChart.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/MergedLinesChart.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/PRChart.tsx
src/pages/ContentScripts/features/repo-star-tooltip/StarChart.tsx

- fix #758
Update minInterval for xAxis in multiple charts

fix: Update minInterval for xAxis in multiple charts

---

src/helpers/get-developer-info.ts
src/pages/ContentScripts/features/repo-fork-tooltip/index.tsx
src/pages/ContentScripts/features/repo-star-tooltip/index.tsx

- fix #775
- fix #777(redundant issue)
After:
https://github.com/hypertrons/hypertrons-crx/assets/32434520/a4f9e04c-40cd-4d21-87fc-cf6ed310fc93

fix: fork and star charts won't show when users are not logged in

---

src/pages/ContentScripts/features/repo-header-labels/index.tsx

fix: header labels don't show up in archived repos

---

package.json
src/pages/ContentScripts/features/oss-gpt/view.tsx
yarn.lock

- resolve #678 
Changed the timestamp in the OSSGPT dialog to the correct format.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://github.com/hypertrons/hypertrons-crx/assets/62098023/c5357208-153f-4e71-a58f-82c8b0fe4a44" alt="Second Image" style="width:100px;"/></td>
<td><img src="https://github.com/hypertrons/hypertrons-crx/assets/62098023/4ecfc95c-4554-467e-b6a3-6e34dc333af0" alt="First Image" …

fix: Changed the timestamp in the OSSGPT dialog to the correct format

---

src/components/Bars.tsx
src/helpers/judge-interval.ts
src/pages/ContentScripts/features/repo-fork-tooltip/ForkChart.tsx
src/pages/ContentScripts/features/repo-header-labels/ActivityChart.tsx
src/pages/ContentScripts/features/repo-header-labels/ContributorChart.tsx
src/pages/ContentScripts/features/repo-header-labels/OpenRankChart.tsx
src/pages/ContentScripts/features/repo-header-labels/ParticipantChart.tsx
src/pages/ContentScripts/features/repo-issue-tooltip/IssueChart.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/MergedLinesChart.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/PRChart.tsx
src/pages/ContentScripts/features/repo-star-tooltip/StarChart.tsx
yarn.lock

- resolve #799
Refactor the duplicate code involved in #792.

refactor: refactor the duplicate code about charts

---

src/pages/ContentScripts/features/perceptor-tab/index.tsx

fix: Perceptor tab missing icon

---

package.json

update the version in package.json

update the version

---

src/api/common.ts
src/constant.ts
src/pages/ContentScripts/features/repo-pr-tooltip/index.tsx

- resolved #881
Change the base URL of oss data .

feat:  change the base URL of oss data

---

src/pages/ContentScripts/features/repo-header-labels/index.tsx
src/pages/ContentScripts/features/repo-header-labels/view.tsx
src/pages/ContentScripts/features/repo-sidebar-labels/index.tsx
src/pages/ContentScripts/features/repo-sidebar-labels/view.tsx
src/pages/ContentScripts/features/repo-star-tooltip/index.tsx
src/pages/ContentScripts/index.scss
src/pages/ContentScripts/index.ts

- resolve #859 
Moved the original label to the right column, filtered the labels with type `xxx-n` and n is not 0, we get rid of the children labels.

fix: tag arrangement problem

---

package.json
src/helpers/get-github-theme.ts
src/helpers/is-github.ts
src/manifest.json
src/pages/ContentScripts/features/developer-activity-openrank-trends/index.tsx
src/pages/ContentScripts/features/developer-hovercard-info/index.tsx
src/pages/ContentScripts/features/developer-networks/index.tsx
src/pages/ContentScripts/features/oss-gpt/index.tsx
src/pages/ContentScripts/features/perceptor-layout/index.tsx
src/pages/ContentScripts/features/perceptor-tab/index.tsx
src/pages/ContentScripts/features/repo-activity-openrank-trends/index.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/index.tsx
src/pages/ContentScripts/features/repo-fork-tooltip/index.tsx
src/pages/ContentScripts/features/repo-header-labels/index.tsx
src/pages/ContentScripts/features/repo-issue-tooltip/index.tsx
src/pages/ContentScripts/features/repo-networks/index.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/index.tsx
src/pages/ContentScripts/features/repo-sidebar-labels/index.tsx
src/pages/ContentScripts/features/repo-star-tooltip/index.tsx
yarn.lock

- resolve #891
Added judgment of Github domain names for feature loading. This way, we can adapt different functions for different websites.

feat: new loading rule for github domains

---

src/pages/ContentScripts/features/developer-networks/index.tsx
src/pages/ContentScripts/features/developer-networks/view.tsx
src/pages/ContentScripts/features/repo-networks/index.tsx
src/pages/ContentScripts/features/repo-networks/view.tsx

- resolve  #889
The routing design for OSGraph has been replaced.

feat: change OSGraph url rule

---

src/helpers/is-github.ts

https://github.com/hypertrons/hypertrons-crx/pull/892
Improved it https://github.com/hypertrons/hypertrons-crx/pull/892.

fix: change to startswith

---

scripts/bump-version.cjs

- resolve https://github.com/hypertrons/hypertrons-crx/issues/894
Modified the comparison strategy of the version, changing string comparison to numerical comparison.

fix: modify version comparison method

---

src/options-storage.ts
src/pages/Options/Options.tsx

feat: disable ossGpt by default

---

src/locales/en/translation.json
src/locales/zh_CN/translation.json
src/pages/ContentScripts/features/fast-pr/index.tsx
src/pages/Sandbox/index.jsx

When encountering poor network connection, it will prompt an error in parsing the URL on any webpage. Therefore, delete it.

fix: optimize fastpr

---

public_configs/fast-pr-url-rules.cjs
src/pages/ContentScripts/features/fast-pr/index.tsx
src/pages/ContentScripts/features/fast-pr/view.tsx

feat: add fast-pr button position

---

src/pages/ContentScripts/features/developer-hovercard-info/index.tsx

- resolve https://github.com/hypertrons/hypertrons-crx/issues/928

fix: fix openrank display

---

src/pages/ContentScripts/features/fast-pr/view.tsx

- reslove https://github.com/hypertrons/hypertrons-crx/issues/931

fix: FastPR title and body modification not take effect

---

package.json
src/pages/ContentScripts/features/fast-pr/index.tsx
src/pages/Sandbox/index.jsx

Previously, every time an iframe was created, the remote file would be pulled again. Now caching has been added, reducing the cost of requesting resources.
And modified the plugin introduction.https://github.com/hypertrons/hypertrons-crx/issues/930

fix: fast-pr sandbox fetch 

---

src/pages/ContentScripts/features/developer-networks/view.tsx
src/pages/ContentScripts/features/repo-networks/view.tsx

- resolve #940 
OSGraph has undergone a new release, supporting more features. At the same time, the OSGraph API also needs to be adapted accordingly.

feat: change osgraph api

---

src/locales/en/translation.json
src/locales/zh_CN/translation.json
src/pages/ContentScripts/features/repo-issue-tooltip/gitee-index.tsx
src/pages/ContentScripts/features/repo-issue-tooltip/view.tsx
src/pages/ContentScripts/index.ts

feat: add gitee issue feature

---

src/pages/ContentScripts/features/repo-fork-tooltip/gitee-index.tsx
src/pages/ContentScripts/features/repo-fork-tooltip/view.tsx
src/pages/ContentScripts/index.ts

feat: add gitee fork

---

src/pages/ContentScripts/features/perceptor-layout/gitee-index.tsx

fix: perceptor
