common/content-script/hypertrons-dashboard.js
common/content-script/simple-graph.js
common/content-script/util.js
common/css/style.css
manifest.json

This PR implements the `SimpleGraph` class based on [`Echarts`](https://echarts.apache.org/zh/index.html). Fix #4. 
First, we need to prepare a DOM container with width and height for ECharts.
```js
graphIdAndClass = "hypertrons-graph-div";
insertLineChart() {
const root = this.getRoot();
if (root) {
root.append(
`<div id="${this.graphIdAndClass}" class="${this.graphIdAndClass}"></div>`
);
}
}
```
Then we can initialize an SimpleGraph instance to create a simple chart:
```js
var lineChart = new SimpleGraph(this.graphIdAndClass,this.getLineChartOption());
```
This is the most powerful interface. All parameters and data can all be passed and modified through `option`. `ECharts` will merge new parameters and data, and then refresh chart. The function can be used to:
Implementing dynamic data …

feat: add SimpleGraph class

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/manifest.json
src/pages/Content/components/DeveloperCollabrationNetwork/index.tsx
webpack.config.js

This commit changes the way that we show information in our extension by using `chrome.i18n`.
From then on, we shouldn't hard-code these information.  
Just add an item in  both `/src/_locales/<zh_CN/en>/messages.json `:  
```json
{
"manifest_appDescription": {
"message": "Hypertrons，您的最佳Github助手"
},
}
```
```json
{
"manifest_appDescription": {
"message": "Hypertrons，your best Github helper"
},
}
```
And use `chrome.i18n.getMessage("manifest_appDescription")` to get the content of it.  
We can switch the default language in browser's settings and see how it will behavior.

feat: add support for i18n

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/OptionsPage/index.css
src/components/OptionsPage/index.tsx
src/components/PopupPage/index.tsx
src/manifest.json
src/pages/Options/index.tsx
src/pages/Popup/index.tsx
src/utils/utils.ts

This commit implements the basic component for `options page` and `popup page` using `Fluent-UI`.  
_We can properly write code for the two pages._
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc..._
_Links to blog posts, patterns, libraries or addons used to solve this problem_

feat: add options page && popup page

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/ExceptionPage/ErrorMessageBar.tsx
src/pages/Content/features/developer-network.tsx
src/pages/Content/features/index.tsx
src/pages/Content/features/project-network.tsx

- add log mechanism to make it easier to debug.
-  catch errors and show the notice to users when something goes wrong.

Feat: add log mechanism

---

src/pages/Background/index.ts
src/services/background.ts
src/services/common.ts
src/utils/metadata.ts

Now user will be lead to a certain page when clicking update notification. The url can be updated in `publish/update_information`
_If this is a relatively large or complex change, kick off the …

feat: jump to certain url when user clicks update notification

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/api/github.ts
src/components/OptionsPage/index.tsx
src/components/PopupPage/index.tsx

Now when logged in, the `popup page` will show user's name and avatar. Also the token will be used in `octokit` api automatically.  
_If this is a relatively large or complex change, kick off the …

feat: github token for popup page

---

src/pages/Content/content.styles.css

Now the width of modal will be 50% of the window's .
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …

fix: modal too narrow when viewing networks

---

package.json
src/components/OptionsPage/index.tsx
src/services/common.ts

Now when clicking `get update` in `options page`, user will be navigated to the right url in `update_information.json`.
_If this is a relatively large or complex change, kick off the discussion …

fix: wrong update url bug

---

src/_locales/en/messages.json
src/_locales/zh_CN/messages.json
src/components/ExceptionPage/ErrorMessageBar.tsx
src/components/ExceptionPage/ErrorPage.tsx
src/components/Graph/Graphin/index.tsx
src/components/OptionsPage/index.tsx
src/components/PopupPage/index.tsx
src/pages/Background/index.ts
src/pages/Content/PerceptorLayout.tsx
src/pages/Content/TeachingBubbleWrapper.tsx

User will be noticed to wait when it would take some time to get data from cdn in `PerceptorLayout` page.  
_If this is a relatively large or complex change, kick off the discussion by explaining …

feat: add loading to perceptor layout

---

src/components/Graph/Graph.tsx
src/pages/Content/DeveloperNetwork.tsx
src/pages/Content/ProjectNetwork.tsx
webpack.config.js

feat: Distinguish the current node from other nodes

---

src/components/DynamicRadar/ControlBar/ControlBar.tsx
src/components/DynamicRadar/DynamicRadar.tsx
src/components/DynamicRadar/Radar/Radar.tsx
src/components/DynamicRadar/SimpleTable/SimpleTable.tsx

This PR implements the "Dynamic Radar" feature requested by #205.
The `DynamicRadar` component consists of 3 sub components: `Radar`, `SimpleTable` and `ControlBar`. These components benefit from the following technologies:
- React functional component
- [`Radar component`](https://echarts.apache.org/zh/option.html#radar) from Echarts
- [`Stack`](https://developer.microsoft.com/en-us/fluentui#/controls/web/stack), [`Slider`](https://developer.microsoft.com/en-us/fluentui#/controls/web/slider), [`IconButton`](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) from Microsoft Fluent UI
`DynamicRadar` is really easy to use and provides features like:
- `light` & `dark` themes
- customizable sizes
- dynamic & interactive
```typescript
import DynamicRadar from …
```

feat: Add DynamicRadar component.

---

package.json
publish/update_information.json
src/pages/Content/ContributorsActivityEvolution.tsx
webpack.config.js

1. Dependencies changes
2. tslint error & webpack options
3. Inconsistent names
The NPM package name was already renamed at #198, but reverted by mistake (as I think) at #210, So I changed it to "hypercrx" again.

fix: build errors introduced by last 2 PRs & inconsistent names

---

src/pages/ContentScripts/DeveloperNetwork.tsx

fix #266 .
This problem is due to an update of css variable naming in GitHub pages.

[css] fix text color on profile page in dark mode

---

package.json
publish/update_information.json
src/pages/ContentScripts/PerceptorLayout.tsx

Thanks for @LiuChangFreeman @heming6666 , The Perceptor page comes back!
fix #305.

[fix] relocate Perceptor Tab for new GitHub page layout

---

package.json
publish/update_information.json
src/mock/background.data.ts
src/pages/ContentScripts/Perceptor.tsx
src/pages/ContentScripts/PerceptorTab.tsx
src/utils/utils.ts

This PR is initiated by https://github.com/hypertrons/hypertrons-crx/issues/276
I created a new function `isPublic` to check the visibility of the current repository. The function simply compares the content of the top-left secondary label and return a Boolean. And I added `isPublic` to the `runsWhen` rules of `PerceptorTab` so that the feature would not be loaded on a private repository at `loadFeatures` phase.

[fix] Only injected public repositories

---

.gitattributes
package.json

#325 
In the PR, I improved the working environment for developers who work on Windows OS
1. Replacing single quote with double quote and an escape character works!
2. It is proved to be the `eof` problem and I added a new file `.gitattributes` to solve it based on [Options Prettier](https://prettier.io/docs/en/options.html#end-of-line) and [.gitattributes in Prettier](https://github.com/prettier/prettier/blob/main/.gitattributes).
1. As for the `eof` problem, it also can be solved by adding attributes to the `.prettierrc` or by adding options to the prettier command. However, based on the links I mentioned above, I selected to add a `.gitattributes` file.
2. Windows users may need to re-clone their repo to enable this change to be effective.
3. More tests may be needed.

[fix] prettier on windows OS

---

publish/update_information.json

- fixes #365
The urls in update_information.json are outdated, which will take users to wrong sites. So update them with the right links.
(None)

chore: update urls in update_information.json

---

src/pages/ContentScripts/DeveloperActiInflTrend.tsx
src/pages/ContentScripts/DeveloperNetwork.tsx
src/pages/ContentScripts/Hypertrons.tsx
src/pages/ContentScripts/PerceptorLayout.tsx
src/pages/ContentScripts/PerceptorTab.tsx
src/pages/ContentScripts/ProjectNetwork.tsx
src/pages/ContentScripts/RepoActiInflTrend.tsx
src/pages/ContentScripts/index.ts

- #383 
I export `DeveloperActiInflTrend`、`RepoActiInflTrend`、`PerceptorTab`... as modules then import them in `ContentScripts/index.ts`.
It is way more easier than I thought. Everything works well as before refactoring.
Also fix a typo in Hypertrons button.
Hey, @wxharry, take a look to this.

refactor: import exported modules rather files

---

src/components/Graph/Graph.tsx
src/pages/ContentScripts/DeveloperActiInflTrend.tsx
src/pages/ContentScripts/RepoActiInflTrend.tsx
src/utils/utils.ts

- fix #400 
I refactored `getGithubTheme` function. Now using dark theme in day time is supported (vice verse).
N.A.

fix: using dark theme in day time or vice verse is not considered

---

src/manifest.json
src/pages/Background/index.ts
src/pages/ContentScripts/DeveloperActiInflTrend.tsx
src/pages/ContentScripts/DeveloperNetwork.tsx
src/pages/ContentScripts/PerceptorLayout.tsx
src/pages/ContentScripts/ProjectNetwork.tsx
src/pages/ContentScripts/index.ts
src/pages/InjectedScripts/index.ts
webpack.config.js

- #382 
It seems navigating between GitHub Tabs/pages will not trigger page reload anymore (like a SPA), which causes that our contentscript will only be run once when we open a tab that matches GitHub url and it damages our extension's core injection function since the contentscript of Hypercrx is designed to be run multiple times for each time the pages are redirected.
Currently, to address this fatal problem, the message passing API supported by chrome extension is applied to trigger `mainInject()` when the url of that tab is changed. The new strategy works but is encountered with unexpected css styles problem. 
All fluentUI elements behave bad after second, third or more `mainInject()` runs, like this:
I spent whole day but did not …

fix: fatal issue 382

---

.github/workflows/release-deploy.yml
package.json
scripts/deploy.js
yarn.lock

- resolve #290
Related [test workflow](https://github.com/tyn1998/workflows-for-hypercrx/runs/7478287061?check_suite_focus=true)：
New secrets:
Well, since I tested the workflow in real environment, a generated 1.7.0 version was uploaded to both chrome webstore and edge add-on store. This is bad, since we cannot upload a smaller version to stores if a bigger version is published.
But fortunately, in edge store we can cancel a publish, and in chrome store we can [defer](https://developer.chrome.com/docs/webstore/publish/#:~:text=%23%20Deferred%20publishing%20option&text=If%20you%20uncheck%20the%20checkbox,once%20the%20review%20is%20complete.) a publish to manually publish it or [drop it](https://stackoverflow.com/a/68568217/10369621) …

ci: automatically deploy to edge add-on store

---

.github/workflows/release-deploy.yml

- resolve #388 
Refer to https://github.com/ncipollo/release-action#action-inputs:
Only commits corresponding to PRs that in **current repo** will be generated as release body, waste so much time here :(
N.A.

ci: release body with contributor login name

---

.github/workflows/release-deploy.yml

- resolve #387
Now files in release assets have version suffix and all compressed files are in zip root dir:
Related test workflow run:
- https://github.com/tyn1998/workflows-for-hypercrx/actions/runs/2723977708

ci: release file names with version number

---

src/components/Graph/Echarts/index.tsx
src/components/Graph/Graph.tsx

- fix #465
I used [`query`](https://echarts.apache.org/zh/api.html#echartsInstance.on) option provided by Echarts to filter those unwanted events.
Now clicking edges won't trigger events:

fix: use `query` to fiter events of Echarts

---

src/views/DeveloperNetworkView/DeveloperNetworkView.tsx

- fix #478
After removing several classes, everything seems good:

fix: modify the css class of the two network buttons in profile perceptor to avoid be truncated

---

README.md

Signed-off-by: frank-zsy <syzhao1988@126.com>
- close #489 
Update installation part in the README file so users can find the link much easier.
N.A.

docs: update readme install

---

src/utils/utils.ts

- fix #504
First I thought it was the change of GitHub UI that should be responsible for  the wrong tab highlight. However, that was not the truth after diving deeper into this issue.
The cause of the issue is in fact due to the popups feature(#455), which changes the DOM structure of the page then the `isPublicRepo()` detector is affected. More specifically, "Public11378" is extracted by the use of `.text()`, which concatenates all text of elements that are selected by …

fix: repoLabel is not recognized right

---

src/views/RepoActiInflTrendView/RepoActiInflTrendView.tsx

- fix #430
Actually the issue does not arise recently, it has been there since the feature came out. When the language is set to Chinese it works well but if we set the language to English the bug appears. Because in English, `seriesName`("Activity") is not equal to `yName`("Act"), the code within that `if` won't be executed.
BTW, `seriesIndex` looks good to me now 😆 https://github.com/hypertrons/hypertrons-crx/pull/456#discussion_r971454350

fix: bars of ActiInflTrend Chart not respond to click when language is English

---

src/views/HypertronsView/HypertronsView.tsx

- style #512 
light mode screenshot
dark mode screenshot
Thanks @wj23027  and @lucky_xmyu :)

style: add dark mode for hypertron command pop up window

---

src/anchors/RepoHeaderLabelsAnchor.tsx

- fix #517
Just adding an `if` branch like which is used in other popups will work. The reason that I didn't do this before is that I thought the header-related DOM elements will not change once the page is initialized. The truth is not.
N.A.

fix: header labels cannot be triggered sometimes

---

src/views/RepoDetailIssueView/IssueChart.tsx
src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
src/views/RepoDetailPRView/PRChart.tsx
src/views/RepoDetailPRView/RepoDetailPRView.tsx

feat: add issue and pr related interaction

---

src/components/Graph/Echarts/index.tsx
src/utils/utils.ts

- resolve #533
Turned `instance.resize()` into a debounce founction so now it will only be triggered 500ms after window resizing stops.
https://user-images.githubusercontent.com/32434520/203568515-950fc929-3717-4aa5-b17a-de2926da65cd.mp4
N.A.

perf: debounce echartsInstance.resize() to avoid pages becoming slow when window being resized

---

src/utils/data.ts

- resolve #541
Now the old date format `yyyym(m)` and the new one `yyyy-mm` can both be correctly parsed so [the change](https://github.com/X-lab2017/open-digger/issues/1074) in OpenDigger will not break functions in Hypercrx.
N.A.

refactor: add wrapper to handle date formatting so json update in OpenDigger will not break Hypercrx

---

src/utils/data.ts

- resolve #543 
I remove the extra code that will be useless after the transition of OpenDigger API in Hypercrx. All charts work well after the update of the code.

chore: remove the extra useless code

---

src/api/common.ts
src/api/developer.ts
src/api/repo.ts
src/components/ExceptionPage/ErrorPage.tsx
src/utils/data.ts
src/utils/request.ts
src/utils/utils.ts
src/views/DeveloperActORTrendView/DeveloperActORTrendView.tsx
src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
src/views/ProjectNetworkView/ProjectNetworkView.tsx
src/views/RepoActORTrendView/RepoActORTrendView.tsx
src/views/RepoDetailForkView/RepoDetailForkView.tsx
src/views/RepoDetailIssueView/IssueChart.tsx
src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
src/views/RepoDetailPRView/MergedLinesChart.tsx
src/views/RepoDetailPRView/PRChart.tsx
src/views/RepoDetailPRView/RepoDetailPRView.tsx
src/views/RepoDetailStarView/RepoDetailStarView.tsx
src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx

- fix #564
The reason why one missing metric file fails the whole PR chart is because we regarded metric files consumed by the PR chart as a whole. In another word, only all data files are ready do the PR chart will show itself in that way.
In this PR, I modified code so a PR chart with some metric missing is allowed:
And I also made some changes in error handling.

fix: PR chart won't show if one of metric files doesn't exist

---

src/utils/data.ts

- fix #583 
- resolve #577
> `originalData` is an object with keys like `2020-01`, `2020-02`, `2022`, `2022-Q1`, `all`.
> A normal month is a key like `2020-01`(yyyy-mm). They are the keys we handle later in this function.
> An unnormal month is a key like `2020`, `2020-Q1`, `all`. They are not used in any feature yet.
In this PR, I just filtered out those unnormal months at the beginning of the function. They will be used in future when we develop features consuming …

fix: some charts are broken because of new data fields like `yyyy-mm-raw`

---

src/utils/utils.ts

- fix #603 
Since most of the search content will be translated to special symbols in the URL , for example ```=``` will be converted to ```%3```. So here the problem can be solved by replacing ```perceptor``` with ```?redirect=perceptor ```.

fix: false positve case of isPerceptor

---

src/components/Graph.tsx

- fix #593 
Added the judgment of whether ths edges is empty.
Now network chart  works  well  when edges are empty.

fix: the network will crash if no edge provided

---

src/pages/ContentScripts/features/perceptor-tab/index.tsx

- close #636 
Remove the highlight class and attribute of perceptor tab after copying from insight tab

fix: wrongly highlight tab

---

src/pages/ContentScripts/index.scss
src/views/DeveloperNetworkView/DeveloperNetworkView.tsx

- fix #647 
The Developer Network/Participated Repos collapses on small screen sizes, due to inappropriate breakpoints , i 've fixed the breakpoints and made necessary changes on the header of the tab that caused the issue  
N.A

fix: fixed collpase issues (#647)

---

src/pages/ContentScripts/index.scss
src/views/DeveloperNetworkView/DeveloperNetworkView.tsx

- fix #649 
Currently the Developer Network/Most Participated Repo  of user profile is not aligned leading to misalignments of the description and the graph I've added appropriate styles to the following components such that they align according to their parent component 
N.A

fix: resolve aligment issues (#649)

---

src/pages/ContentScripts/features/oss-gpt/view.tsx

- fix #624 
The react-chat-widget has bug in itself for it's resizing props, may be because it had event listener all over the container, so we don't use the inbuilt property of resizing instead we use jquery to select the container and allow it resize only when the left border of the container is dragged we watch for mutations in the useeffect when the conversation container becomes active 
N.A

fix: abnormal-width on text select

---

src/pages/ContentScripts/features/repo-fork-tooltip/index.tsx

-  fix #663 
Relocating the chart to the left side of the fork button. Now, default popup will occupy minimal space, and the chart's title is clearly visible. 
N.A.

fix: repositioning the fork chart

---

src/helpers/get-developer-info.ts

- resolve #684 
- The problem is that when requesting data after setting additional personal information, wrong parameters will be passed in, as shown in the circle on the console on the right side of the figure below:
- In the code, additionally use the `split` method to intercept the string before the space to solve this problem.

fix: truncate redundant profile information

---

.gitignore
src/api/repo.ts
src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/pages/ContentScripts/features/repo-activity-racing-bar/RacingBar.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/index.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/view.tsx
src/pages/ContentScripts/index.scss
src/pages/ContentScripts/index.ts

- resolve #687 
I have laid a foundation for this feature, which can be viewed in the option list. But the actual functionality has not yet been implemented. I'll follow up as soon as I have time!

feat: add Repo Activity Racing Bar

---

src/pages/ContentScripts/features/repo-activity-racing-bar/data.ts
src/pages/ContentScripts/features/repo-activity-racing-bar/view.tsx

- resolve #750 
1. Add a function `getMonthlyData` to extract only the monthly data.
2. Use the above function to filter monthly data from `repoActivityDetails`.

fix: duplicate numbers on repo-activity-racing-bar

---

src/pages/ContentScripts/features/developer-networks/react-modal.scss
src/pages/ContentScripts/features/oss-gpt/rcw.scss
src/pages/ContentScripts/features/repo-activity-racing-bar/PlayerButton.tsx
src/pages/ContentScripts/features/repo-activity-racing-bar/SpeedController.tsx
src/pages/ContentScripts/index.scss

fix: adapt for new GitHub color variables

---

src/pages/ContentScripts/features/repo-fork-tooltip/ForkChart.tsx
src/pages/ContentScripts/features/repo-fork-tooltip/view.tsx
src/pages/ContentScripts/features/repo-header-labels/ActivityChart.tsx
src/pages/ContentScripts/features/repo-header-labels/ContributorChart.tsx
src/pages/ContentScripts/features/repo-header-labels/OpenRankChart.tsx
src/pages/ContentScripts/features/repo-header-labels/ParticipantChart.tsx
src/pages/ContentScripts/features/repo-issue-tooltip/IssueChart.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/MergedLinesChart.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/PRChart.tsx
src/pages/ContentScripts/features/repo-star-tooltip/StarChart.tsx

- resolve #762
https://github.com/hypertrons/hypertrons-crx/assets/135088663/0db03a95-1e12-4af3-9877-af2e1a9e3dad

enhancement: modify the display effect on the xAxis of tooltip charts

---

src/locales/en/messages.json
src/locales/zh_CN/messages.json
src/pages/ContentScripts/features/oss-gpt/service.ts
src/pages/ContentScripts/features/oss-gpt/view.tsx

- resolve #774
**Since the backend service is deprecated, I added a message prompt that OSS-GPT is deprecated. As shown below:**
**Correspondingly, there are also message in English:**

chore: add message prompt that GPT conversation backend is deprecated

---

src/pages/ContentScripts/components/NativePopover.tsx

- fix #817
Add an click event listener for hiding the popover when the anchor element is clicked. In this way, the popover is cleared by a React method`unmountComponentAtNode` rather by the GitHub code.

fix: native popover broken after tab switch

---

src/pages/ContentScripts/features/repo-star-tooltip/index.tsx

fix: start chart not show when repo is unstarred

---

src/api/repo.ts

- Fix #820 
The contributors data will be correctly displayed as active contributors instead of new contributors
For example, the CONTRIBUTORS of the Redis project should be 4 instead of 0, and now it has been corrected。

fix: Contributors data is now displayed correctly

---

src/pages/ContentScripts/components/NativePopover.tsx
src/pages/ContentScripts/features/developer-hovercard-info/view.tsx

#825
#832
Fixed the issue of GitHub action trigger button not displaying.
https://github.com/user-attachments/assets/13fadd1f-3f21-4aa4-8d6f-b07ac2aa6163
Changed the style in https://github.com/hypertrons/hypertrons-crx/pull/832 to better match the native style on GitHub.

fix: fix action trigger button

---

src/pages/ContentScripts/features/developer-hovercard-info/index.tsx

Related issues #842 
- keyword #xxx
Thanks to Yantong's help, OpenRank can now be displayed normally in most scenarios.

fix: repo homepage latest commit hovercard openrank display

---

package.json
src/pages/ContentScripts/features/developer-networks/react-modal.scss
src/pages/ContentScripts/features/oss-gpt/rcw.scss
src/pages/ContentScripts/features/repo-header-labels/view.tsx
src/pages/Options/Options.css
yarn.lock

Related issues 
#807 
Thanks to Yantong's help, OpenRank can now be displayed normally in most scenarios.
Background Information: The meta file exported by OpenDigger now includes label data.
Objective: To add this label data to the project page for better display of label information.
Reference: You can refer to the file at https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/meta.json, which lists all labels for the OpenDigger project.
results:

[OSS101] Task 3: Display OpenDigger labels in the right of the repository header #807

---

src/pages/ContentScripts/features/repo-activity-racing-bar/data.ts

fix: reserved digits for the length of the contributor bar 

---

src/pages/ContentScripts/features/perceptor-tab/index.tsx

- keyword #862 
https://github.com/user-attachments/assets/78f138af-6111-4b9d-94f9-3fc8e72709b1

fix: fix Perceptor tab refresh preblom

---

src/pages/ContentScripts/features/repo-star-tooltip/index.tsx

- resolved #874 
After clicking the star button, the page no longer displays the star image unless the page is refreshed.

fix: repo star tooltip

---

src/pages/ContentScripts/features/repo-star-tooltip/index.tsx

N.A.
After clicking the star button, the page no longer displays the star image unless the page is refreshed.

fix: Star button hover inactive after click

---

scripts/deploy.js

https://github.com/hypertrons/hypertrons-crx/issues/884
The return of uploadRes is an `item`, which can be changed to `JSON. stringify (uploadRes, null, 2)` to indicate the error message. The return information of Edge's `publishResp` is a string. To capture its erroneous information, it became a `try... catch...`.

fix: Modify deployment error message

---

src/manifest.json

Delete permissions that are not used but requested from chrome.
* notifications
* alarms
* cookies

fix: Delete unnecessary permissions

---

src/helpers/get-developer-info.ts
src/helpers/get-repo-info.ts

- related to #773 
Added a method to retrieve the repository name via page elements, while also retaining the option to retrieve it from the URL. This ensures that even if the names obtained by both methods differ in case, the result parsed from page elements takes priority. This approach also allows for fallback to URL-based retrieval in case of GitHub page structure changes.

fix: Added a way to retrieve repository names through the page

---

.github/workflows/publish_configs.yml
public_configs/fast-pr-url-rules.js
scripts/test_configs.js

- #901 
This PR contains public config file, test and publish actions workflow:
- `public_configs/fast-pr-url-rules.js`: This file is the rules config file for FastPR, and other more static public configs file can be located in this directory in the future. I also add tests to each rule to check if the rule is valid.
- `scripts/test_configs.js`: This file is used to test the result of config files. Right now only FastPR configs need to be tested.
- …

feat: add public configs for FastPR

---

public_configs/fast-pr-url-rules.cjs

- 
Fix FastPR config rules for kwdb

fix: fix kwdb config rules of fastpr

---

public_configs/fast-pr-url-rules.cjs
src/pages/ContentScripts/features/fast-pr/index.tsx
src/pages/ContentScripts/features/fast-pr/view.tsx

Single page application loading issue.

fix: kaiwu db load

---

src/pages/Background/index.ts
src/pages/ContentScripts/features/fast-pr/index.tsx
src/pages/ContentScripts/features/fast-pr/view.tsx

- keyword #905
https://github.com/user-attachments/assets/4f172172-bd80-475f-9845-188ae9f7d016
When the user selects text, the button will move to the last position of the mouse. When the mouse scrolls, the button will return to its original position.Scroll back to its original position only after selecting text, and remain in the dragged position after dragging.
Except https://www.kaiwudb.com/kaiwudb_docs. Because the construction of their document website is an …

feat: improve fast pr in selecting text

---

public_configs/fast-pr-url-rules.cjs

Update the FastPR config for OpenDigger website. The editor should only take effect for docs and blogs, but not other page like front page or leaderboard, playground.

fix: fix configs for opendigger website

---

src/helpers/get-developer-info.ts

The method for obtaining the developer's name is incorrect, resulting in the name of the logged in user being consistently obtained instead of the developer's name. Related repairs have been made.

fix: fix the method of obtaining developer names

---

src/pages/ContentScripts/features/fast-pr/view.tsx

- resolve #932 
Modified the position logic of the fastpr button. Modify according to this behavior:
When select the text, the button should stay with the text even when page scrolls. Actually, the button position should follow the text if the page scrolls. When the selected text scroll out of the page, the button should go back to initial position.
When user unselect text, the button should go back to initial position. …

fix: FastPR edit button postion

---

src/helpers/get-gitee-repo-info.ts
src/pages/ContentScripts/features/repo-activity-openrank-trends/gitee-index.tsx
src/pages/ContentScripts/features/repo-activity-openrank-trends/view.tsx
src/pages/ContentScripts/index.ts

- resloved https://github.com/hypertrons/hypertrons-crx/issues/962

feat: add repo Activity & OpenRank Trends

---

src/pages/ContentScripts/features/repo-sidebar-labels/gitee-OpenDiggerLabel.tsx
src/pages/ContentScripts/features/repo-sidebar-labels/gitee-index.tsx
src/pages/ContentScripts/index.ts

feat: Migrate repo labels to Gitee

---

src/helpers/get-gitee-developer-info.ts
src/helpers/get-gitee-repo-info.ts
src/helpers/get-github-developer-info.ts
src/helpers/get-github-repo-info.ts
src/helpers/get-platform.ts

fix: console error

---

src/helpers/get-gitee-repo-info.ts
src/pages/ContentScripts/features/repo-header-labels/gitee-index.tsx
src/pages/ContentScripts/features/repo-header-labels/view.tsx
src/pages/ContentScripts/features/repo-pr-tooltip/gitee-index.tsx

fix:KWDB does not display

---

src/pages/ContentScripts/features/perceptor-tab/gitee-index.tsx

- keyword #981 
Modified the conditions for the appearance of the perceptor-tab. In Gitee, the repository must have metadata (meta.json) before it is displayed.

fix: Perceptor tab always shows for Gitee repo
